name: Apk Build

on:
#  push:
#    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

concurrency:
  group: blank-${{ github.ref }}
  cancel-in-progress: true

jobs:

  distribution:

