name: Apk Build

on:
#  push:
#    branches: [ "master" ]
  workflow_run:
    workflows: ["Code Quality Checks"]   # Match the exact name from android-test.yml
    branches: ["master"]
    types: ["completed"]

  workflow_dispatch:

concurrency:
  group: blank-${{ github.ref }}
  cancel-in-progress: true

jobs:

  distribution:
    name: Build signed apk
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Testing
        run: echo hi
