name: 📦 Send APK via Discord on Release
on:
  pull_request:
    branches: [ "master" ]

#  release:
#    types: [published]

  workflow_dispatch:


#concurrency:
#  group: blank-${{ github.ref }}
#  cancel-in-progress: true


jobs:

  distributeApk:
    runs-on: ubuntu-latest

    steps:

      - name: Download the latest APK asset
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: '*.apk'
          out-file-path: 'apk-download'
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: List downloaded files (for debugging)
        run: |
          echo "Files in apk-download:"
          ls -R apk-download

      - name: Determine downloaded APK
        run: |
         FILE=$(ls apk-download/*.apk | head -n1)
         echo "APK_FILE=$FILE" >> $GITHUB_ENV   


      - name: Determine downloaded APK
        run: |
          FILE=$(ls apk-download/*.apk | head -n1)
          echo "APK_FILE=$FILE" >> $GITHUB_ENV           

      - name: Send latest release link to Discord
        uses: tsickert/discord-webhook@v7
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            🚀 A new release is live!
            👉 [Click here to download the latest APK](https://github.com/shalenMathew/Quotes-app/releases/latest/download/${{ env.APK_FILE }})
          wait: true

