name: 📦 Send APK via Discord on Release
on:
  pull_request:
    branches: [ "master" ]

#  release:
#    types: [published]

  workflow_dispatch:


concurrency:
  group: blank-${{ github.ref }}
  cancel-in-progress: true


jobs:

  distributeApk:
    runs-on: ubuntu-latest

    steps:

      - name: Download the latest APK asset
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: '*.apk'
          out-file-path: 'apk-download'
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: List downloaded files (for debugging)
        run: |
          echo "Files in apk-download:"
          ls -R apk-download
          
      - name: Send APK to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
              New release **${{ github.release.tag_name }}** is live!
          filename: apk-download/*.apk
          wait: true